In [4]:
import numpy as np
A =np.array([1, 2, 3, 4, 5]) 
np.argmax(A)


4

In [5]:
for n in range(8, 0, -1):
    print(n)

8
7
6
5
4
3
2
1


In [8]:
 for i, j in np.ndindex((7, 5)):
        print(i, j)

0 0
0 1
0 2
0 3
0 4
1 0
1 1
1 2
1 3
1 4
2 0
2 1
2 2
2 3
2 4
3 0
3 1
3 2
3 3
3 4
4 0
4 1
4 2
4 3
4 4
5 0
5 1
5 2
5 3
5 4
6 0
6 1
6 2
6 3
6 4


In [5]:
D= np.array([[8.85440000e-06, 0.00000000e+00, 0.00000000e+00, 2.48613983e-17,
        0.00000000e+00],
       [0.00000000e+00, 3.00406859e-08, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 2.23130880e-13, 1.60852733e-11, 0.00000000e+00,
        1.01707158e-20],
       [0.00000000e+00, 0.00000000e+00, 5.10691660e-15, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 1.03419392e-10, 5.59958385e-15, 0.00000000e+00,
        2.01357071e-15],
       [0.00000000e+00, 0.00000000e+00, 5.32840899e-11, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.81619925e-12,
        0.00000000e+00]])

D.shape
# T = 0, 1, 2, 3, 4
np.argmax(D, axis=0)

array([0, 1, 5, 6, 4], dtype=int64)

In [13]:
D[:,2]

array([0.00000000e+00, 0.00000000e+00, 1.60852733e-11, 5.10691660e-15,
       5.59958385e-15, 5.32840899e-11, 0.00000000e+00])

In [9]:
x = np.array([[4,2,9], [1,0,46]])
index_array = np.argmax(x, axis=0)
index_array

array([0, 0, 1], dtype=int64)

In [28]:
max_ind = np.array([0, 1, 2, 6, 4])
prob = []
for i, j in enumerate(max_ind):
    print(i, j)
    print(D[j, i])
    prob.append(D[j, i])
#     prob = prob * D[i, j]
prob

0 0
8.8544e-06
1 1
3.00406859e-08
2 2
1.60852733e-11
3 6
1.81619925e-12
4 4
2.01357071e-15


[8.8544e-06, 3.00406859e-08, 1.60852733e-11, 1.81619925e-12, 2.01357071e-15]

In [18]:
for i, j in enumerate(max_ind):
    print(i, j)

0 0
1 1
2 2
3 6
4 4


 np.ndindex((7, 5))

In [ ]:
max = [Tag1- > tag2 ->]

In [6]:
for n in range(3, 0, -1):
        print(n)

3
2
1


In [9]:
for n in range(0, 3, 1):
        print(n)

0
1
2


In [11]:
A = ["shivam", "ksh"]
for i, j in enumerate(A):
    print(i, j)

0 shivam
1 ksh


In [16]:
TAGS_IDX = np.array([1, 9, 76, 2, 3, 4, 5, 6])
for i in np.nditer(TAGS_IDX):
    print(i)

1
9
76
2
3
4
5
6


In [ ]:
# 1nd Approach Complex Way: But This wrong I Guess Need to Confirm
TAGS_PROBS=np.ones(Sequence_Count)
for ix, iy in np.ndindex(Viterbi_Matrix.shape):
    if(ix==0):
     TAGS_PROBS[iy]=(Viterbi_Matrix[ix,iy])
    else:
        if(Viterbi_Matrix[ix,iy]>TAGS_PROBS[iy]):
            TAGS_PROBS[iy]=Viterbi_Matrix[ix,iy]


In [18]:
# Max_Indices can also be replaced simply By but Need to Cross Check
MAX_POS = np.argmax(Viterbi_Matrix, axis=0)

In [15]:
len(TAGS_IDX)

6

In [23]:
DIC = {('Brainpower 2', 'NNP'): 0.0008016032064128256, (', 3', ','): 0.998959958398336, ('not 4', 'RB'): 0.0674729471674093, ('physical 5', 'JJ'): 0.0020655822359927703, ('plant 6', 'NN'): 0.2080706179066835, (', 7', ','): 0.998959958398336, ('is 8', 'VBZ'): 0.33689839572192515, ('now 9', 'RB'): 0.03500954805856143, ('a 10', 'DT'): 0.2767615714967393, ('firm 11', 'NN'): 0.0009007386056566384, ("'s 12", 'POS'): 0.9446308724832215, ('chief 13', 'JJ'): 0.003356571133488252, ('asset 14', 'NN'): 0.0005404431633939831, ('. 15', '.'): 0.9920424403183024}
for k in list(DIC.keys()):
    print(k[1])

NNP
,
RB
JJ
NN
,
VBZ
RB
DT
NN
POS
JJ
NN
.
